### ISSUE TITLE
Make Luis Cabaceira admin of this repository

### ISSUE THREAD

**Issue by maoo** [AlfrescoArchive/alfresco-indexer#19]
To allow Luis to lead this project and deploy new releases, we followed the onboarding instructions from http://central.sonatype.org/pages/ossrh-guide.html but we still need to allow him write/admin access to this repository.

Can you please grant Admin rights to @cabaceira on this project?

**Comment by enzor** [comment]
I am not the owner of this repo. @bmlong137 has the final say on that before i do anything

**Comment by bmlong137** [comment]
Go ahead with Luis.

On Jan 20, 2017 6:10 AM, Enzo Rivello <notifications@github.com> wrote:

I am not the owner of this repo. @bmlong137<https://github.com/bmlong137> has the final say on that before i do anything

**Comment by enzor** [comment]
@cabaceira you got an email! :)

**Comment by maoo** [comment]
All done, thank you!
